baseurl = "https://personal.kh-corp.me"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  #contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  # Show reading time in minutes for posts
  showReadingTime = false
  contentTypeName = "posts"
  
  
  [[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1
  
  [[menu.main]]
    name = "Whoami"
    url = "/about"
    weight = 3
    


[languages]
  [languages.en]
    title = "Heorhii Khrabrov"
    subtitle = "Linux Systems Engineer"
    keywords = ""
    copyright = "© 2020 kh.corp"
    menuMore = "Show more"
    writtenBy = "Heorhii Khrabrov"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "/dev/ops"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  
